### ISSUE TITLE
deriveAvro / parse schema error

### ISSUE THREAD

**Issue by forficate** [haskell-works/avro#116]
`derriveAvro` fails when a primitive type is defined as an object, i.e. :
```
{
  "name": "CREATETIME",
  "type": {
    "type": "long",
    "connect.version": 1,
    "connect.name": "org.apache.kafka.connect.data.Timestamp"
  }
}
```

According to Schema Declaration (https://avro.apache.org/docs/current/spec.html#schemas):

> A Schema is represented in JSON by one of:
>    - A JSON string, naming a defined type.
>    - A JSON object, of the form:
>
>   {"type": "typeName" ...attributes...}
>
>    where typeName is either a primitive or derived type name, as defined below. Attributes not defined in this document are permitted as metadata, but must not affect the format of serialized data.
>
>    - A JSON array, representing a union of embedded types.

So in the example type given it should be parsed as a primitive `long` and the additional fields `["connect.version", "connect.name"]`, captured as metadata or ignored.

It looks like the `Nothing` case at https://github.com/haskell-works/avro/blob/c5484e3499a275f616455d771e80b785842c3d62/src/Data/Avro/Schema.hs#L344 falls through for non primitives.

**Comment by torgeirsh** [comment]
Will you make a pull request? I'm also running into the same problem.

**Comment by forficate** [comment]
I had forgot about this. I planned to make a PR but was having issues getting the tests to run trying `cabal new-test`. It now looks to be working and was a local env issue so will make a PR now.
