### ISSUE TITLE
Question relative to integer types encoding

### ISSUE THREAD

**Issue by Bebere** [haskell-works/avro#14]
Hi,

Just a question: the Quickstart documentation states that the `Int` and `Int64` Haskell types are matched with the `long` Avro type. However, in `Data.Avro.Encode`, `Int` and `Int64` use `avroInt` instead of `avroLong` for their `EncodeAvro` instances. Is that normal?

**Comment by AlexeyRaga** [comment]
It is most likely a bug, thanks for pointing out.
`Int` is trickier, but `Int64` should be encoded as `Long` IMO.  Also because `Int64` has a `Decode` instance that reads `Long` [2]
@newhoggy what do you think?

[1] https://github.com/haskell-works/hw-haskell-avro/blob/master/src/Data/Avro/Encode.hs#L132
[2]

**Comment by AlexeyRaga** [comment]
Interestingly, we actually have a set of tests here that asserts `Long` values decoding/encoding, and somehow it manages to work: https://github.com/GaloisInc/avro/blob/master/test/Avro/Codec/Int64Spec.hs#L70

**Comment by AlexeyRaga** [comment]
It looks like the encoding process doesn't actually use that type annotation:
```
newtype AvroM = AvroM { runAvro :: (Builder,Type) }

class EncodeAvro a where
  avro :: a -> AvroM

putAvro :: EncodeAvro a => a -> Builder
putAvro   = fst . runAvro . avro
```

so `putAvro` takes a tuple of `(Builder, Type)` and throws away the type. And underlying `encodeRaw`, `Zig`, etc. have all the correct implementations.
Maybe this is how it all works. 

We may want to figure out the intent and clean it up at some point. But for now, we can probably fix the `Encode` instance for `Int`/`Int64` to be annotated as `Long`.
