### ISSUE TITLE
Add support for blocks compression 

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell-works/avro#53]
Avro spec (https://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files) allows blocks within containers to be compressed.

This lib already supports such compression one way (when reading containers). It would be nice if compression was supported for both reading and writing containers.

**Comment by alexbiehl** [comment]
We are very interested and would like to make it happen. I noticed we were using `pure-zlib` for inflation. However, it doesn't support deflation! Is there a particular reason you chose `pure-zlib` over `zlib`?

**Comment by AlexeyRaga** [comment]
It was chosen by the original author, not by us. 
I believe the reason might be that `pure-zlib` is pure and that it is maintained by the original author's company. I can't think of any other functional reasons, but again, I cannot know.
