### ISSUE TITLE
Add better support for logical types

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell-works/avro#68]
Currently, logical types [1] are only supported "on the way in". We can correctly parse/decode schemas with logical types, but then the information about logical types is gone.

Ideally, we should preserve logical types in `Schema`.

[1] https://avro.apache.org/docs/1.8.2/spec.html#Logical+Types

**Comment by TikhonJelvis** [comment]
I need this for something I'm building, so I was thinking of implementing it. 

Do you have any thoughts on what this should look like? Right now, I would probably just add the logical types to the `Schema` type and update the rest of the library from there.

@alexbiehl @imalsogreg—any thoughts?

**Comment by imalsogreg** [comment]
@TikhonJelvis Great! So the design possibilities are:
 - Add constructors for Date, Day, TimeMillis, TimeMicros, TimestampMilles, etc to `data Schema = ...`
 - For a constructor that may optionally get a logical attribute, add a record field for that (e.g., extend the Fixed constructor with `isDuration :: Bool`, extend `Int` with `isDate :: Bool`, etc.
 - Add `logicalType :: Text` field to each schema type that supports it.

First option sounds best to me, too.

**Comment by serras** [comment]
Has been any progress on this? I am happy to contribute a patch.

**Comment by AlexeyRaga** [comment]
@serras I don't think there was any progress on this feature.

This is indeed a feature that I would really like to see implemented, but I haven't thought about it seriously yet.

Avro Specification says that logical types are declared in Schema as:

```javascript
{
  "type": "bytes",
  "logicalType": "decimal",
  "precision": 4,
  "scale": 2
}
```

so we could look at the schema at TH time and generate appropriate types. 

We should also take into account these edge cases:

> If a logical type is invalid, for example a decimal with scale greater than its precision, then implementations should ignore the logical type and use the underlying Avro type.

It'd be awesome if you can help making it happen! Thanks for that!

**Comment by AlexeyRaga** [comment]
@serras @serras do you think it would potentially be possible to make logical types extensible?
For example, defining a schema like this seems to be possible:

```
{
  "type": "int",
  "logicalType": "ipv4"
}
```
or
```
{
  "type": "fixed",
  "size": "5",
  "logicalType": "cidrv4"
}
```

and then in my application I would somehow instruct the library which type to use for a given logical type.

I am not asking you to implement it my any means, just a thought that occurred in my mind and may have occurred in your too :)

**Comment by serras** [comment]
I could well imagine having something like this. The main issues I see are:
- How do you know how to translate those logical types into Haskell types? That is, how do you make the relation between the logical type `uuid` and the `UUID` type?
- What happens if a logical type can have more than one different underlying type?

**Comment by AlexeyRaga** [comment]
Yeah, that's the problem.
Maybe through instances or by providing `deriveAvro` with some explicit set of types/functions...

Anyway, thanks :)
