### ISSUE TITLE
Are we actually using hpack?

### ISSUE THREAD

**Issue by TikhonJelvis** [haskell-works/avro#73]
Right now, we have both a `.cabal` file *and* a `package.yaml` file in the repo. This is redundant and can cause problems—for example, #71 only updated the `.cabal` file, so the repo does not build with hpack any more. This was not caught by our CI which, presumably, just uses the `.cabal` file directly.

Ideally, we should only have one or the other. I propose getting rid of `package.yaml` altogether and sticking to a normal `.cabal` file.

**Comment by TikhonJelvis** [comment]
This was causing problems on our codebase at work because our Haskell builder ignores the `.cabal` file if a `package.yaml` file is present in a repo, but the master branch currently doesn't build with the `package.yaml`.

**Comment by AlexeyRaga** [comment]
Well, I agree.
Yes, we use `hpack` (and `stack` understands it natively). I guess we can get rid of `.cabal` from the repo.

**Comment by AlexeyRaga** [comment]
We don't use it anymore
