### ISSUE TITLE
Add a benchmark suite

### ISSUE THREAD

**Issue by TikhonJelvis** [haskell-works/avro#80]
Performance matters when serializing and deserializing large amounts of data with `avro`. It would be great to have a benchmark suite to measure and track performance:

  * how long it takes to serialize/deserialize `Avro.Value` to binary
  * how much memory the package uses (including just the memory efficiency of `Avro.Value`s)

This will help us make informed decisions about the performance of the package going forwards.

**Comment by TikhonJelvis** [comment]
I can put together a simple initial set of benchmarks for serialization and deserialization, but I could definitely use help to flesh out the benchmarks themselves after I set it up.

**Comment by AlexeyRaga** [comment]
Great idea!
Thanks for doing it, I am sure that we are going to contribute to the set of benchmarks once it is set up.
